'use client'
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/WebChat/Sidebar/MinSidebar";
import Searchbar from '../components/WebChat/SearchBar/searchbar';
import ChatNavbar from '../components/WebChat/ChatFilter/FilterSec';
import LandingChat from '../components/WebChat/ChatSection/LandingChat';
import FriendsList from '../components/WebChat/UserBar/FriendsList';
// import Loading from "../loading";
// import Sidebar from "./components/Sidebar/MinSidebar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
           <div>
      
      <div style={{ display: "flex"}}>
     <Sidebar/>
      <div style={{ display: "block"}}>
     <ChatNavbar/>
      {children}
     </div>
        </div>
      </div>
      
      </body>
    </html>
  );
}
